################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/CMSIS/CMSIS_DSP/Source/InterpolationFunctions \
Drivers/STM32F4xx_HAL_Driver/Src \
FreeRTOS/FreeRTOS-Kernel \
FreeRTOS/FreeRTOS-Kernel/portable/Common \
FreeRTOS/FreeRTOS-Kernel/portable/GCC/ARM_CM4F \
FreeRTOS/FreeRTOS-Kernel/portable/MemMang \
grapics/demos/benchmark/assets \
grapics/demos/benchmark \
grapics/demos/keypad_encoder \
grapics/demos/music/assets \
grapics/demos/music \
grapics/demos/stress \
grapics/demos/widgets/assets \
grapics/demos/widgets \
grapics/env_support/rt-thread \
grapics/env_support/rt-thread/squareline \
grapics/examples/anim \
grapics/examples/assets \
grapics/examples/assets/emoji \
grapics/examples/event \
grapics/examples/get_started \
grapics/examples/layouts/flex \
grapics/examples/layouts/grid \
grapics/examples/libs/bmp \
grapics/examples/libs/ffmpeg \
grapics/examples/libs/freetype \
grapics/examples/libs/gif \
grapics/examples/libs/png \
grapics/examples/libs/qrcode \
grapics/examples/libs/rlottie \
grapics/examples/libs/sjpg \
grapics/examples/others/fragment \
grapics/examples/others/gridnav \
grapics/examples/others/ime \
grapics/examples/others/imgfont \
grapics/examples/others/monkey \
grapics/examples/others/msg \
grapics/examples/others/snapshot \
grapics/examples/porting \
grapics/examples/scroll \
grapics/examples/styles \
grapics/examples/widgets/animimg \
grapics/examples/widgets/arc \
grapics/examples/widgets/bar \
grapics/examples/widgets/btn \
grapics/examples/widgets/btnmatrix \
grapics/examples/widgets/calendar \
grapics/examples/widgets/canvas \
grapics/examples/widgets/chart \
grapics/examples/widgets/checkbox \
grapics/examples/widgets/colorwheel \
grapics/examples/widgets/dropdown \
grapics/examples/widgets/img \
grapics/examples/widgets/imgbtn \
grapics/examples/widgets/keyboard \
grapics/examples/widgets/label \
grapics/examples/widgets/led \
grapics/examples/widgets/line \
grapics/examples/widgets/list \
grapics/examples/widgets/menu \
grapics/examples/widgets/meter \
grapics/examples/widgets/msgbox \
grapics/examples/widgets/obj \
grapics/examples/widgets/roller \
grapics/examples/widgets/slider \
grapics/examples/widgets/span \
grapics/examples/widgets/spinbox \
grapics/examples/widgets/spinner \
grapics/examples/widgets/switch \
grapics/examples/widgets/table \
grapics/examples/widgets/tabview \
grapics/examples/widgets/textarea \
grapics/examples/widgets/tileview \
grapics/examples/widgets/win \
grapics/src/core \
grapics/src/draw/arm2d \
grapics/src/draw \
grapics/src/draw/nema_gfx \
grapics/src/draw/nxp/pxp \
grapics/src/draw/nxp/vglite \
grapics/src/draw/renesas \
grapics/src/draw/sdl \
grapics/src/draw/stm32_dma2d \
grapics/src/draw/sw \
grapics/src/draw/swm341_dma2d \
grapics/src/extra/layouts/flex \
grapics/src/extra/layouts/grid \
grapics/src/extra/libs/bmp \
grapics/src/extra/libs/ffmpeg \
grapics/src/extra/libs/freetype \
grapics/src/extra/libs/fsdrv \
grapics/src/extra/libs/gif \
grapics/src/extra/libs/png \
grapics/src/extra/libs/qrcode \
grapics/src/extra/libs/rlottie \
grapics/src/extra/libs/sjpg \
grapics/src/extra/libs/tiny_ttf \
grapics/src/extra \
grapics/src/extra/others/fragment \
grapics/src/extra/others/gridnav \
grapics/src/extra/others/ime \
grapics/src/extra/others/imgfont \
grapics/src/extra/others/monkey \
grapics/src/extra/others/msg \
grapics/src/extra/others/snapshot \
grapics/src/extra/themes/basic \
grapics/src/extra/themes/default \
grapics/src/extra/themes/mono \
grapics/src/extra/widgets/animimg \
grapics/src/extra/widgets/calendar \
grapics/src/extra/widgets/chart \
grapics/src/extra/widgets/colorwheel \
grapics/src/extra/widgets/imgbtn \
grapics/src/extra/widgets/keyboard \
grapics/src/extra/widgets/led \
grapics/src/extra/widgets/list \
grapics/src/extra/widgets/menu \
grapics/src/extra/widgets/meter \
grapics/src/extra/widgets/msgbox \
grapics/src/extra/widgets/span \
grapics/src/extra/widgets/spinbox \
grapics/src/extra/widgets/spinner \
grapics/src/extra/widgets/tabview \
grapics/src/extra/widgets/tileview \
grapics/src/extra/widgets/win \
grapics/src/font \
grapics/src/hal \
grapics/src/misc \
grapics/src/widgets \
grapics/tests/makefile \
grapics/tests/src \
grapics/tests/src/test_cases \
grapics/tests/src/test_fonts \
grapics/tests/unity \
grapics/ui \

